CREATE DATABASE `igd` DEFAULT CHARACTER SET `utf8`;
USE `igd`;
CREATE TABLE `drinking` (id INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT);
ALTER TABLE `drinking` ADD `status` TINYINT  NULL  DEFAULT NULL  AFTER `id`;
ALTER TABLE `drinking` ADD `comment` VARCHAR(255)  NULL  DEFAULT NULL  AFTER `status`;
ALTER TABLE `drinking` ADD `latitude` DOUBLE  NULL  DEFAULT NULL  AFTER `comment`;
ALTER TABLE `drinking` ADD `longitude` DOUBLE  NULL  DEFAULT NULL  AFTER `latitude`;
ALTER TABLE `drinking` ADD `created` TIMESTAMP  NOT NULL  DEFAULT CURRENT_TIMESTAMP  AFTER `longitude`;
